DO $$ BEGIN
  CREATE TYPE "CaptureApprovalStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE "CaptureFisheriesRecord"
  ADD COLUMN IF NOT EXISTS "extensionOfficerName" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "extensionOfficerPhone" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "farmerNumber" TEXT,
  ADD COLUMN IF NOT EXISTS "gender" "Gender" NOT NULL DEFAULT 'MALE',
  ADD COLUMN IF NOT EXISTS "ageBracket" "AgeBracket" NOT NULL DEFAULT 'ADULT',
  ADD COLUMN IF NOT EXISTS "topics" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS "activeCages" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "inactiveCages" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "latitude" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "longitude" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "approvalStatus" "CaptureApprovalStatus" NOT NULL DEFAULT 'PENDING',
  ADD COLUMN IF NOT EXISTS "approvedById" TEXT,
  ADD COLUMN IF NOT EXISTS "approvedAt" TIMESTAMP(3);

CREATE INDEX IF NOT EXISTS "CaptureFisheriesRecord_approvalStatus_idx" ON "CaptureFisheriesRecord"("approvalStatus");
