ALTER TABLE "License" ALTER COLUMN "status" SET DEFAULT 'PENDING';

UPDATE "License" SET "type" = 'FISHERMAN' WHERE "type"::TEXT = 'ARTISANAL_FISHING';
UPDATE "License" SET "type" = 'FISH_TRADER' WHERE "type"::TEXT = 'COMMERCIAL_FISHING';
UPDATE "License" SET "type" = 'FISHERMAN' WHERE "type"::TEXT = 'AQUACULTURE';
